configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/enerfi.yaml # network model configuration
    - configs/datasets/renbody/0013_01.yaml # dataset usage configuration
    - configs/specs/optimized.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        near: 2.0
        far: 12.0
        render_ratio: 0.5
        # prettier-ignore
        ratio: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35]

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
